export interface Person {
  id: number;
  first_name: string;
  last_name: string;
  email: string;
  gender: string;
  ip_address: string;
}

export const persons: Person[] = [
  {
    id: 1,
    first_name: 'Milty',
    last_name: 'Sibylla',
    email: 'msibylla0@apache.org',
    gender: 'Agender',
    ip_address: '217.124.83.228',
  },
  {
    id: 2,
    first_name: 'Theadora',
    last_name: 'Hagard',
    email: 'thagard1@spiegel.de',
    gender: 'Female',
    ip_address: '83.243.26.13',
  },
  {
    id: 3,
    first_name: 'Mariel',
    last_name: 'Tarney',
    email: 'mtarney2@npr.org',
    gender: 'Polygender',
    ip_address: '135.94.1.96',
  },
  {
    id: 4,
    first_name: 'Morley',
    last_name: 'Phare',
    email: 'mphare3@dot.gov',
    gender: 'Female',
    ip_address: '74.220.34.32',
  },
  {
    id: 5,
    first_name: 'Susi',
    last_name: 'Densun',
    email: 'sdensun4@wunderground.com',
    gender: 'Bigender',
    ip_address: '149.4.171.75',
  },
  {
    id: 6,
    first_name: 'Davie',
    last_name: 'Neaves',
    email: 'dneaves5@telegraph.co.uk',
    gender: 'Bigender',
    ip_address: '140.204.63.13',
  },
  {
    id: 7,
    first_name: 'Alexandros',
    last_name: 'Dyerson',
    email: 'adyerson6@sbwire.com',
    gender: 'Genderfluid',
    ip_address: '254.163.87.52',
  },
  {
    id: 8,
    first_name: 'Eugenius',
    last_name: 'Overthrow',
    email: 'eoverthrow7@prnewswire.com',
    gender: 'Female',
    ip_address: '229.224.212.253',
  },
  {
    id: 9,
    first_name: 'Randie',
    last_name: 'Bastock',
    email: 'rbastock8@ox.ac.uk',
    gender: 'Genderfluid',
    ip_address: '183.73.132.10',
  },
  {
    id: 10,
    first_name: 'Ollie',
    last_name: 'MacFaul',
    email: 'omacfaul9@wikia.com',
    gender: 'Polygender',
    ip_address: '112.102.72.68',
  },
  {
    id: 11,
    first_name: 'Vassily',
    last_name: 'Showen',
    email: 'vshowena@weebly.com',
    gender: 'Female',
    ip_address: '254.122.230.7',
  },
  {
    id: 12,
    first_name: 'Michal',
    last_name: 'Dutton',
    email: 'mduttonb@gnu.org',
    gender: 'Agender',
    ip_address: '245.98.81.245',
  },
  {
    id: 13,
    first_name: 'Bale',
    last_name: 'Felten',
    email: 'bfeltenc@cdbaby.com',
    gender: 'Polygender',
    ip_address: '227.154.36.220',
  },
  {
    id: 14,
    first_name: 'Jazmin',
    last_name: 'Arghent',
    email: 'jarghentd@geocities.com',
    gender: 'Genderfluid',
    ip_address: '66.15.250.244',
  },
  {
    id: 15,
    first_name: 'Maurizio',
    last_name: 'Gosalvez',
    email: 'mgosalveze@adobe.com',
    gender: 'Non-binary',
    ip_address: '30.209.132.0',
  },
  {
    id: 16,
    first_name: 'Annabella',
    last_name: 'Phillipp',
    email: 'aphillippf@paypal.com',
    gender: 'Male',
    ip_address: '207.187.22.57',
  },
  {
    id: 17,
    first_name: 'Rey',
    last_name: 'Wesgate',
    email: 'rwesgateg@xing.com',
    gender: 'Polygender',
    ip_address: '98.225.13.175',
  },
  {
    id: 18,
    first_name: 'Portia',
    last_name: 'Gorner',
    email: 'pgornerh@ow.ly',
    gender: 'Bigender',
    ip_address: '233.233.74.145',
  },
  {
    id: 19,
    first_name: 'Ainsley',
    last_name: 'Schoular',
    email: 'aschoulari@theglobeandmail.com',
    gender: 'Genderfluid',
    ip_address: '216.12.51.99',
  },
  {
    id: 20,
    first_name: 'Stefania',
    last_name: 'de Almeida',
    email: 'sdealmeidaj@xinhuanet.com',
    gender: 'Genderqueer',
    ip_address: '237.101.184.237',
  },
];
